version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/JsonValidate"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/JsonValidate.JSInterop"
    schedule:
      interval: "weekly"      
  - package-ecosystem: "nuget"
    directory: "/test/JsonValidate.Test"
    schedule:
      interval: "weekly"
